import { NextRequest, NextResponse } from "next/server";
import { briefProducts } from "../../../lib/brief-products";
import { verifyScopeConfirmationToken } from "../../../lib/scope-confirmation";
import { createStripeCheckoutSession } from "../../../lib/stripe-checkout";
export const runtime="nodejs";
function escapeHtml(value:string){return value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
export async function GET(request:NextRequest){
 const token=request.nextUrl.searchParams.get("token")||"",secret=process.env.SCOPE_APPROVAL_SECRET||"",apiKey=process.env.RESEND_API_KEY||"",fromEmail=process.env.RESEND_FROM_EMAIL||"",replyTo=process.env.ORDER_NOTIFICATION_EMAIL||"";
 const siteUrl=request.nextUrl.origin.replace(/\/$/,"");
 if(!secret||!apiKey||!fromEmail||!replyTo||!process.env.STRIPE_SECRET_KEY)return new NextResponse("Scope confirmation is not configured.",{status:500});
 const payload=verifyScopeConfirmationToken(token,secret);if(!payload)return new NextResponse("This approval link is invalid or has expired.",{status:400});
 if(payload.product!=="standard")return new NextResponse("Quick Scan does not use scope confirmation. Use the direct-payment Quick Scan flow.",{status:409});
 const product=briefProducts.standard,amountUsdCents=14900;
 let checkout;
 try{checkout=await createStripeCheckoutSession({requestId:payload.requestId,product:"standard",productName:product.name,amountUsdCents,customerName:payload.customerName,customerEmail:payload.email,companyLegalName:payload.companyLegalName,companyChineseName:payload.companyChineseName,registrationNumber:payload.registrationNumber,jurisdiction:payload.jurisdiction,siteUrl});}
 catch(error){console.error("Stripe checkout creation failed:",error);return new NextResponse("Unable to create the secure Stripe checkout.",{status:502});}
 const customerName=escapeHtml(payload.customerName),companyName=escapeHtml(payload.companyLegalName),requestId=escapeHtml(payload.requestId),productName=escapeHtml(product.name),price="US$149",timing=escapeHtml(product.timing);
 const html=`<div style="font-family:Arial,sans-serif;line-height:1.6;color:#111;max-width:640px;margin:0 auto"><p style="font-size:12px;letter-spacing:.12em;text-transform:uppercase">Sericant Limited</p><h1 style="font-size:28px;line-height:1.15">Scope confirmed</h1><p>Dear ${customerName},</p><p>We have reviewed your request concerning <strong>${companyName}</strong> and can proceed with the research.</p><div style="border:1px solid #d9d6cc;padding:18px 20px;margin:24px 0"><p style="margin:0 0 8px"><strong>Research product:</strong> ${productName}</p><p style="margin:0 0 8px"><strong>Confirmed fee:</strong> ${price}</p><p style="margin:0 0 8px"><strong>Estimated delivery:</strong> ${timing} after payment and receipt of sufficient identifying information</p><p style="margin:0"><strong>Reference:</strong> ${requestId}</p></div><p>Please use the secure Stripe checkout below to accept the confirmed scope and complete payment.</p><p style="margin:28px 0"><a href="${escapeHtml(checkout.url)}" style="display:inline-block;background:#111;color:#fff;text-decoration:none;padding:14px 20px;font-weight:700">PAY US$149 SECURELY →</a></p><p style="font-size:13px;color:#555">Research begins after payment is confirmed. Stripe checkout reference: ${escapeHtml(checkout.id)}.</p><p>Regards,<br/>Sericant Limited<br/>Hong Kong<br/><a href="https://www.sericant.com">sericant.com</a></p></div>`;
 const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({from:fromEmail,to:[payload.email],reply_to:replyTo,subject:`${payload.requestId} — Scope Confirmed — ${payload.companyLegalName}`,html})});
 if(!response.ok){console.error("Scope confirmation email failed:",await response.text());return new NextResponse("Unable to send the scope confirmation email.",{status:502});}
 return new NextResponse(`<!doctype html><html><body style="font-family:Arial,sans-serif;padding:48px;color:#111"><h1>Scope confirmation sent.</h1><p>${requestId} — ${companyName}</p><p>US$149 Stripe Checkout ${escapeHtml(checkout.id)} has been created and emailed to the customer.</p><p>You can close this window.</p></body></html>`,{headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store"}});
}
